import Link from "next/link";

import { DashboardNav } from "@/components/organisms/dashboard-nav";
import { getUserRoles, requireAnyRole, roleManagerRoles } from "@/lib/permissions/roles";
import { createAdminClient } from "@/lib/supabase/admin";

export default async function AdminNotificationsPage() {
  await requireAnyRole(roleManagerRoles);
  const roles = await getUserRoles();
  const supabase = createAdminClient();
  const { data: notifications } = await supabase
    .from("notifications")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(100);
  const userIds = [...new Set((notifications ?? []).map((notification) => notification.user_id))];
  const { data: profiles } = userIds.length
    ? await supabase.from("profiles").select("id, email, full_name").in("id", userIds)
    : { data: [] };
  const profileMap = new Map((profiles ?? []).map((profile) => [profile.id, profile]));

  return (
    <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-8 px-4 py-10 sm:px-6 lg:px-8">
      <DashboardNav roles={roles} />
      <section>
        <h1 className="text-4xl font-semibold">Portal notifications</h1>
        <p className="mt-3 text-muted-foreground">Review recent in-app notifications generated by portal workflows.</p>
      </section>
      <section className="rounded-lg border bg-card shadow-sm">
        <div className="divide-y">
          {(notifications ?? []).map((notification) => {
            const profile = profileMap.get(notification.user_id);

            return (
              <article className="grid gap-3 p-5 text-sm lg:grid-cols-[1fr_1fr_auto]" key={notification.id}>
                <div>
                  <h2 className="font-medium">{notification.title}</h2>
                  <p className="mt-1 text-muted-foreground">{notification.message}</p>
                </div>
                <div>
                  <p>{profile?.full_name || profile?.email || notification.user_id}</p>
                  <p className="text-muted-foreground">{notification.notification_type}</p>
                </div>
                {notification.action_url ? (
                  <Link className="font-medium text-primary hover:underline" href={notification.action_url}>
                    Open
                  </Link>
                ) : null}
              </article>
            );
          })}
          {notifications?.length === 0 ? <p className="p-5 text-sm text-muted-foreground">No notifications yet.</p> : null}
        </div>
      </section>
    </main>
  );
}
